# Generated by Django 4.0.4 on 2022-07-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='upload_cv',
            field=models.FileField(blank=True, null=True, upload_to='upload/cv/'),
        ),
    ]
