# Generated by Django 4.0.4 on 2022-07-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_upload_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='upload_cv',
            field=models.FileField(default=1, upload_to='upload/cv/'),
            preserve_default=False,
        ),
    ]
