# Generated by Django 4.0.4 on 2022-05-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_content_video_content_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='owner',
        ),
    ]
