# Generated by Django 4.0.4 on 2022-06-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_comment_course_comment_course_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='course_video',
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_comments', to='courses.course'),
            preserve_default=False,
        ),
    ]
