# Generated by Django 4.0.4 on 2022-06-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_comment_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rate',
            new_name='rating',
        ),
    ]
