# Generated by Django 4.0.4 on 2022-07-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_content_video_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='video_watched',
        ),
    ]
