# Generated by Django 4.0.4 on 2022-07-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_courseprogress_content_courseprogress_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='percentage_value',
            field=models.IntegerField(default=0),
        ),
    ]
