# Generated by Django 4.0.4 on 2022-07-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_courseprogress_percentage_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_progress', to='courses.course'),
        ),
    ]
