# Generated by Django 3.1.1 on 2020-10-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20201012_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='volume_remaining',
            field=models.IntegerField(default=3600),
        ),
    ]
