# Generated by Django 3.1.1 on 2020-10-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_usermembership_volume_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='storage_size',
            field=models.IntegerField(default=3600),
        ),
    ]
