# Generated by Django 3.1.2 on 2020-10-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20201015_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='storage_size',
            field=models.IntegerField(default=648000),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='volume_remaining',
            field=models.IntegerField(default=648000),
        ),
    ]
