# Generated by Django 3.1.2 on 2020-10-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20201016_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='storage_size',
            field=models.IntegerField(default=10800),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='volume_remaining',
            field=models.IntegerField(),
        ),
    ]
