# Generated by Django 3.1.2 on 2020-11-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_auto_20201022_1405'),
        ('subscriptions', '0005_auto_20201015_2055'),
    ]

    operations = [
    ]
