# Generated by Django 3.1.6 on 2021-06-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_auto_20201119_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
