# Generated by Django 3.1.6 on 2021-06-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_auto_20210622_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='UserSubscription',
        ),
    ]
