# Generated by Django 3.1.6 on 2021-07-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_auto_20210625_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Standard', 'standard'), ('Free', 'free')], default='Free', max_length=30),
        ),
    ]
