# Generated by Django 3.1.6 on 2021-07-12 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_auto_20210702_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='user_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_membership_subscription', to='subscriptions.usermembership'),
        ),
    ]
