# Generated by Django 3.1.6 on 2021-07-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_auto_20210712_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_badge',
            field=models.BooleanField(default=False),
        ),
    ]
