# Generated by Django 3.1.6 on 2021-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_usersubscription_subscription_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscription_badge',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='subscription_badge',
            field=models.BooleanField(default=False),
        ),
    ]
