# Generated by Django 4.0.4 on 2022-05-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_remove_membership_storage_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Premium', 'premium'), ('Free', 'free')], default='Free', max_length=30),
        ),
    ]
